- name: precheck
  hosts: ne_list
  gather_facts: false
  connection: netconf
    
  vars:
    ansible_ssh_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
    ansible_network_os: 'junos'

  vars_files:
    - ./vars/neBaseInfo.yml
    
  roles:
    - { role: "getFacts" }
    - { role: "md5check" }
    - { role: "precheck" }