- name: ringcheck
  hosts: ring_check_ne
  gather_facts: false
  connection: netconf
    
  vars:
    ansible_ssh_user: "{{ username }}"
    ansible_ssh_pass: "{{ password }}"
    ansible_network_os: 'junos'

  roles:
    - { role: "ringCheck" }